baseurl = "https://sad-leakey-dac828.netlify.com/"
title = "Shap's Bytes"

languageCode = "en-us"
theme ="cactus-pro"
googleAnalytics="UA-141257382-1"
hasCJKLanguage = false

[params]
    name = "Shap's Bytes"
    description = "Bits about tech"
    bio = "*Your future is created by what you do today, ~~not tomorrow~~*"
    twitter = "theshapguy"

[social]
    twitter  = "https://www.twitter.com/theshapguy"
    github   = "https://www.github.com/theshapguy"
