baseurl = "https://theshapguy.com/"
title = "Shap's Bytes"

languageCode = "en-us"
theme ="cactus-pro"
[params]
    name = "Shap's Bytes"
    description = "Bits about tech and politics"
    bio = "*Your future is created by what you do today, ~~not tomorrow~~*"
    twitter = "theshapguy"

[social]
    twitter  = "https://www.twitter.com/theshapguy"
    github   = "https://www.github.com/theshapguy"
